### ISSUE TITLE
Find error, quoted string issue

### ISSUE THREAD

**Issue by neilscudder** [fhs/gompd#26]
Trying to call Find("artist \"David Bowie\"") threw ACK 2@0 too few args. 

Removed quote function from client.go, and it works. (line 554: id, err := c.cmd("find " + quote(uri)) )

Is there a correct way to pass this argument through the quote function without having to bypass it? The quote function is beyond my comprehension.

**Comment by fhs** [comment]
I've just pushed some changes that I think fixes this issue.

Try: `Find("artist", "David Bowie")`
