### ISSUE TITLE
Handle connection lost to MPD

### ISSUE THREAD

**Issue by paulogr** [fhs/gompd#37]
Hi, congrats for the this lib.

I'm just new here and trying to find a way to handle the connection lost to MPD.

I'm doing some tests and when I kill MPD the client are killed too.

How to handle it?

Thank you.

**Comment by zefer** [comment]
Hi @paulogr. I have a fairly simple solution for this that has been rock solid for years. I'm sure it could be more elegant, though. A goroutine periodically checks the connection (with `client.Ping()`) and reconnects if necessary. https://github.com/zefer/mothership/blob/master/mpd/client.go#L20.
