### ISSUE TITLE
Adopt new Go modules correctly

### ISSUE THREAD

**Issue by BernardZhao** [fhs/gompd#49]
Currently in my `go.mod`, this module displays as `github.com/fhs/gompd v2.0.0+incompatible`. I search this up and found that this is supposed to happen when:
> If a repository has not opted in to modules but has been tagged with valid semver tags, meanwhile, it's a v2+ module

I am using Golang version 1.13.

On a related note, for some reason I am also not getting the most recent version of this library when I use modules, which I believe may be due to this? When I delete my `go.mod` and `go.sum` my change in #48 is expressed, but when I make it a module suddenly the bug it fixes appears. Any idea on how to avoid this?

**Comment by BernardZhao** [comment]
After investigating, it appears that golang seems to be automatically fetching version 2.0.0, which doesn't have a `go.mod`, meaning that it has not opted in to modules, resulting in the incompatible. Not sure how to fix this

**Comment by fhs** [comment]
Isn't the `+incompatible` is just information? See:
https://github.com/golang/go/wiki/Modules#can-a-module-consume-a-v2-package-that-has-not-opted-into-modules-what-does-incompatible-mean

I think there is some `+incompatible` changes coming in go1.14: https://tip.golang.org/doc/go1.14

You need to change your import path to `github.com/fhs/gompd/v2` to use the latest version of gompd.

**Comment by BernardZhao** [comment]
I just changed my import path to `github.com/fhs/gompd/v2` and got:
```
build github.com/BernardZhao/Jukebox: cannot load github.com/fhs/gompd/mpd/v2: module github.com/fhs/gompd@latest found (v2.0.0+incompatible), but does not contain package github.com/fhs/gompd/mpd/v2
```

Am I doing something wrong?

**Comment by fhs** [comment]
Sorry, I meant `github.com/fhs/gompd/v2/mpd`. The `v2` goes after the repository root.

**Comment by fhs** [comment]
I think it's too late to fix the `+incompatible` issue from our side. The go tool might change what version it fetches when do you do `go get` (see [go1.14 release notes](https://tip.golang.org/doc/go1.14)).
