### ISSUE TITLE
Add support for mpd partitions

### ISSUE THREAD

**Issue by Stapper** [fhs/gompd#63]
Mpd has a feature called partitions. A partition is one frontend of a multi-player MPD process: it has separate queue, player and outputs. A client is assigned to one partition at a time.

https://www.musicpd.org/doc/html/protocol.html#partition-commands

Following should be added to client.go
```
//Partition commands

// Partition Switches the client to a different partition.
func (c *Client) Partition(name string) error {
	return c.Command("partition %s", name).OK()
}

// ListPartitions Print a list of partitions and their information.
func (c *Client) ListPartitions() ([]Attrs, error) {
	return c.Command("listpartitions").AttrsList("partition")
}

// NewPartition creates a new partition with the given name.
func (c *Client) NewPartition(name string) error {
	return c.Command("newpartition %s", name).OK()
}

// DelPartition deletes partition with the given name.
func (c *Client) DelPartition(name string) error {
	return c.Command("delpartition %s", name).OK()
}

// MoveOutput Move an output with the given name to the current partition.
func (c *Client) MoveOutput(name string) error {
	return c.Command("moveoutput %s", name).OK()
}
```

I have added this in my local branch, but it is not yet fully tested, as my mpd version on my dev machine does not yet support this feature, and I am currently having issues with updating it to the most recent version.
Should I sent a pull request, when I have fully tested this?

**Comment by fhs** [comment]
Sure, send a pull request. Some unit tests would be good also.
