### ISSUE TITLE
How long should connections stay alive?

### ISSUE THREAD

**Issue by codesoap** [fhs/gompd#65]
This isn't really an issue, but rather a question. I created a `Client` when my program starts and was trying to reuse it after that. When my program doesn't send requests for some time and then tries to send one after that, I get `read tcp [::1]:13364->[::1]:6600: read: connection reset by peer` or `EOF`. Here is an example on how to reproduce the problem:

```
package main

import "github.com/fhs/gompd/mpd"
import "time"

func main() {
	c, _ := mpd.Dial("tcp", "localhost:6600")
	time.Sleep(time.Minute)
	if err := c.Pause(true); err != nil {
		panic(err)
	}
}
```

Am I supposed to create a new `Client` for every event that I create? If so: Would you take a pull request, where I document this, or do you think this is common knowledge?

**Comment by fhs** [comment]
The [protocol documentation](https://www.musicpd.org/doc/html/protocol.html) says this:
> While a client is waiting for idle results, the server disables timeouts, allowing a client to wait for events as long as mpd runs.

The `ping` command might also work to keep the connection alive.

That said, I think if you care about a persistent connection, you should handle disconnects anyway. You can lose the TCP connection anytime the server or client loses network.

**Comment by codesoap** [comment]
Thanks for the quick response! I was aware, that the connection stays alive while waiting for a response to the `idle` command. In the documentation you referenced "timeouts" are mentioned, but unfortunately it's never explained which timeouts exist and what their durations are.

> The `ping` command might also work to keep the connection alive.
I was not looking for a way to "make it work", but trying to find out what the best practice is. I take it, that keeping a connection alive (while not in `idle`) is not considered a normal use case and I'll instead create a new `Client` for every command. Thanks for the clarification!

> That said, I think if you care about a persistent connection, you should handle disconnects anyway. You can lose the TCP connection anytime the server or client loses network.

Good point. I'll think about how to do this. Maybe something like a `DialWithAutoReconnect` function would be possible.
